  - name: backport patches to 8.15 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.15
    actions:
      backport:
        assignees:
          - "{{ author }}"
        labels:
          - "backport"
        branches:
          - "8.15"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
